#!/bin/sh

unalias -a

##############
### PACMAN ###
##############

if [ -f "/etc/arch-release" ]; then
	alias S='paru -S'
	alias R='paru -R'
	alias Q='paru -Q'
	alias U='yes | paru -Scc && paru -Syyuu'
	alias C='paru -Rcns $(paru -Qdtq) --noconfirm && yes | paru -Scc'
fi

###########
### BUN ###
###########

b="$BUN_INSTALL/bin/bun"
alias bun="use b"
alias ba="$b add"
alias br="$b run"
alias bs="$b run start"
alias bb="$b run build"
alias bd="$b run dev"
alias bf="$b run fmt"
alias bi="$b i"
alias bu="$b update"
alias bug="$b update -g"
alias bur="$b upgrade && $b update -g"
alias big="$b i -g"
alias bid="$b i -D"
alias binit="$b init"
alias bc="rms *lock* && rms .next && rms node_modules && bi"

alias nextjs="$b x create-next-app@latest --typescript --eslint --tailwind --app --turbopack  --src-dir --use-bun"

alias bx="use alias for bx"
alias bunx="bx"
alias knip="$b x knip"
alias lint="$b x eslint"
alias pret="$b x prettier"
alias bcn="$b x shadcn@latest add"

##############
### PRISMA ###
##############

pam() {
	zwx="$b x prisma migrate"
	arg="$1"
	shift
	case "$arg" in
	r | reset) $zwx reset "$@" ;;
	v | resolve) $zwx resolve "$@" ;;
	s | status) $zwx status "$@" ;;
	d | deploy) $zwx deploy "$@" ;;
	+) $zwx dev --name $arg "$@" ;;
	*) printf "pam r: reset\npam s: status\npam d: deploy\npam <name> dev --name <name>\n" ;;
	esac
}

pa() {
	zw="$b x prisma"
	arg="$1"
	shift
	case "$arg" in
	o | studio) $zw studio "$@" ;;
	i | init) $zw init "$@" ;;
	g | gen | generate) $zw generate "$@" ;;
	pl | pull) $zw db pull "$@" ;;
	s | seed) $zw db seed "$@" ;;
	ph | push) $zw db push "$@" ;;
	v | validate) $zw validate "$@" ;;
	m | migrate) printf "use pam\n" ;;
	*) printf "pa o: studio\npa i: init\npa g: generate\npa pl: db pull\npa psh: db push\npa s: db seed\npa v: validate\n" ;;
	esac
}

############
### RUST ###
############

c="$CARGO_HOME/bin/cargo"
alias cargo="use c"
alias cn="$c +nightly"
alias cii="$c init"
alias ct="$c test"
alias cb="$c build"
alias cbr="$c build --release"
alias cr="$c run"
alias crr="$c run --release"
alias ccl="$c clean"
alias cdoc="$c doc"
alias cdocall="$c doc --document-private-items --all"
alias cnew="$c new"
alias ca="$c add"
alias crm="$c remove"
alias cu="$c uninstall"
alias cf="cn fmt --all -- --unstable-features --error-on-unformatted"
alias cfmt="use cf"
alias cy="$c clippy --all"
alias ciu="$c install-update -a -g"

alias cw=" watchexec -e rs -r cargo run"

alias crd="$c run --features debug"


alias gy='echo -e "\n#![warn(missing_docs,warnings,deprecated_safe,future_incompatible,keyword_idents,let_underscore,nonstandard_style,refining_impl_trait,rust_2018_compatibility,rust_2018_idioms,rust_2021_compatibility,rust_2024_compatibility,unused,clippy::all,clippy::pedantic,clippy::style,clippy::perf,clippy::complexity,clippy::correctness,clippy::restriction,clippy::nursery,clippy::cargo)]\n#![allow(clippy::single_call_fn,clippy::implicit_return,clippy::pattern_type_mismatch,clippy::blanket_clippy_restriction_lints,clippy::missing_trait_methods,clippy::question_mark_used,clippy::mod_module_files,clippy::module_name_repetitions,clippy::pub_with_shorthand,clippy::unseparated_literal_suffix,clippy::else_if_without_else)]\n" | x'

alias chk="cls && rms Cargo.lock && export RUSTDOCFLAGS='-D warnings' && cargo +nightly clippy --all -- --verbose -D warnings && cargo +nightly build --release --verbose && cargo +nightly test && cargo +nightly doc --document-private-items --all && cargo +nightly fmt --all -- --unstable-features --error-on-unformatted && cargo +nightly tarpaulin --fail-under 100"

alias gcio='echo -n $(catt $CMD/secret/cratesio.txt) | xclip'

rp="$CARGO_HOME/bin/rustup"
alias rustup="use rp"
alias rpt="$rp toolchain"
alias rpd="$rp default"
alias rpu="$rp update"
alias rpv="$rp --version"
alias rpc="$rp component"
alias rpca="$rp component add"

alias rnone="export RUST_BACKTRACE=0"
alias rtr="export RUST_BACKTRACE=1"


##############
### TERMUX ###
##############

alias tmux="use t0 or tx"
alias tx="/usr/bin/tmux"
alias t0='tx a -t 0 || tmux new -s 0'
alias t1='tx a -t 1 || tmux new -s 1'
alias t2='tx a -t 2 || tmux new -s 2'

###########
### IWD ###
###########

alias iw="sudo iwctl"
alias iw0="iw station wlan0"
alias iwc="sudo iwctl station wlan0 connect"
alias iwd="sudo iwctl station wlan0 disconnect"
alias iwgh="iws; while :; do cls; iwg; sleep 1; done"
alias iwg="iw0 get-networks"
alias iws="iw0 scan"

###########
### GIT ###
###########

alias idd="/usr/bin/id"

i="/usr/bin/git"
alias git="use i"
alias iv="$i --version"
alias ic="$i commit -m"
alias id="$i diff"
alias ii="$i init"
alias is="$i status"
alias ia="$i add"
alias iam="$i commit --amend"
alias ibr="$i branch"
alias il="$i log"
alias ilo="$i log --oneline"
alias ils="$i ls-files"
alias iph="$i push"
alias ifh="$i push --force"
alias irt="$i remote"
alias irta="$i remote add"
alias ipl="$i pull"
alias irb="$i rebase"
alias iro="$i restore"
alias iros="$i restore --staged"
alias isec="$i secrets"
alias irs="$i reset"
alias irt="$i remote"
alias ish="$i stash"
alias icfg="$i config"
alias icfgg="$i config --global"

alias checks="gh pr checks"
alias ghs="gh search"
alias repo="gh search repos"
alias w="gh repo view -w"

##############
### PYTHON ###
##############

alias python="use py"
alias py="/usr/bin/python"
alias serve="py -m http.server"

###############
### SYSTEMD ###
###############

alias systemctl="use ctl or ctll"

alias ctl="sudo /usr/bin/systemctl"
alias ctll="/usr/bin/systemctl"
alias ctlu="ctl list-unit-files"

alias journalctl="use jctl or jctll"
alias jctl="sudo /usr/bin/journalctl"
alias jctll="/usr/bin/journalctl"

alias restart="use ts"
alias start="use ta"
alias status="use tt"
alias stop="use to"

alias reboot="use tb"
alias sd="use td"
alias slp="use tl"

alias tu='ctl suspend'
alias tb="sudo /usr/bin/reboot"
alias tbf="sudo /usr/bin/reboot --force"
alias td="shutdown -P now -h"

_ctl_def() {
	if [ -z "$3" ]; then
		p="ctl"
	else
		p="$3"
	fi

	alias "ta$1"="$p start $2"
	alias "ts$1"="$p restart $2"
	alias "tt$1"="$p status $2"
	alias "to$1"="$p stop $2"
}

_ctl_def
_ctl_def "iw" "iwd"
_ctl_def "rd" "systemd-resolved"
_ctl_def "net" "iwd systemd-resolved"
_ctl_def "sql" "postgresql"
_ctl_def "au" "--user pipewire.socket wireplumber pipewire-pulse.socket" "ctll"

###########
### SEE ###
###########

alias l="use s"
alias ls="l"
alias la="l"
alias ll="use sv"
alias lla="ll"
alias eza="ll"
alias llag="ll"
alias cat="use s"
alias bat="use sv"

alias ggcode="use gc"
alias gcode="use gc"
alias gcv="gc v"
alias ga="gc aliases"
alias gk="gc keymaps.lua"

alias pwdf="use pf"
alias pf="readlink -f"
alias px='echo -n $(pwd) | x'

############
### GUI ####
############

alias xdg-open="use o"
alias ws='open https://synapses.telecom-paris.fr/login?type=Shib'
alias we='open https://ecampus.paris-saclay.fr/my/'

###############
### NETWORK ###
###############

alias get="curl -X GET"
alias post="curl -X POST"
alias pi="ping std.rs"

s="/usr/bin/ssh"
alias ssh="use aliases for ssh"
alias rpi="$s uname@$RPIIP"
alias mssh="$s mad@mad-ssh.rezel.net -J twebber-23@ssh.enst.fr"
alias tessh="use tesh"
alias tesh="$s root@telecom-etude.rezel.net -J twebber-23@ssh.enst.fr"
alias pssh='$s twebber-23@perso-twebber-23.lxc.enst.fr -J twebber-23@ssh.enst.fr'
alias gssh="s $FILES/.ssh/id_ed25519.pub | x && s $FILES/.ssh/id_ed25519.pub"
alias enst='ssh twebber-23@ssh.enst.fr'

#############
### PUSHD ###
#############

alias p="pushd >/dev/null"
alias pp="popd >/dev/null"
alias push="use p"
alias pop="use pp"
alias j="pp"
alias k="p .."

alias cd="use p"
alias src="p src"

_gt() {
	alias "$1"="cls && p $2 && sv"
}

_gt 2a "$FILES/2a"
_gt a7 "$FILES/2a/a7"
_gt a8 "$FILES/2a/a8"
_gt a8 "$FILES/2a/a8"
_gt apps "$APPS"
_gt cache "$HOME/.cache"
_gt ces "$FILES/2a/cesure"
_gt cf "$CONFIG"
_gt cmd "$CMD"
_gt d "$DEV"
_gt data "$DATA"
_gt db "$FILES/2a/db"
_gt del "$FILES/.waste"
_gt dev "$DEV"
_gt dot "$DOT"
_gt emailrs "$DEV/email"
_gt en "$FILES/2a/en"
_gt en "$FILES/2a/en"
_gt etc "$ETC"
_gt f "$FILES"
_gt h "$HOME"
_gt html "$DEV/html-filter"
_gt inf "$FILES/2a/inf224"
_gt jc "$DEV/jc"
_gt mail "$DEV/mailbox"
_gt md "$DEV/md-viewer"
_gt ml "$FILES/2a/ml"
_gt pars "$DEV/c-parser"
_gt pdelc "$DEV/.c/"
_gt pdelr "$DEV/.r/"
_gt perso "$DEV/personal-website"
_gt s1 "$FILES/2a/s1"
_gt s2 "$FILES/2a/s2"
_gt s4 "$FILES/2a/s4"
_gt s5 "$FILES/2a/s5"
_gt s5 "$FILES/2a/s5"
_gt s6 "$FILES/2a/s6"
_gt s8 "$FILES/2a/s8"
_gt s8 "$FILES/2a/s8/hb_detector"
_gt sp "$FILES/2a/sp"
_gt sw "$DEV/sw"
_gt tp3 "$FILES/2a/s5/git/td3"
_gt vsh "$DEV/vimsh"
_gt words "$DEV/words"

############
### EDIT ###
############

alias hx="helix"

alias delc="e $DEV/.c/"
alias delr="e $DEV/.r/"
alias vi="use e"
alias vim="vi"
alias nvim="vi"

alias bspwmrc="use bsp"
alias bsp="e $CONFIG/bspwm/bspwmrc"
alias sxhkdrc="use sx"
alias se="sudo $EDITOR"
alias sx="e $CONFIG/sxhkd/sxhkdrc"

alias rm='use rms'
alias rmm="/usr/bin/rm"
alias rms=". rms"
alias gsaved="s $CMD/data/saved.txt"
alias esaved="e $CMD/data/saved.txt"

alias touch="use n"
alias n="/usr/bin/touch"

alias ep="edt profile"
alias ea="edt aliases"
alias ce="use edt"
alias nf="use edt"

###############
### HELPERS ###
###############

eb=$(echo $b | sed -E 's/([\/.])/\\\1/g')
alias b="alias | g 'bun ' | sed -E 's/^alias |$eb //g;s/=/\t/' | tr -d \' | g -v 'b\t'"

ecg=$(echo $c | sed -E 's/([\/.])/\\\1/g')
alias c="alias | g 'cargo ' | sed -E 's/^alias |$ecg //g;s/=/\t/' | tr -d \' | g -v 'c\t'"

erp=$(echo $rp | sed -E 's/([\/.])/\\\1/g')
alias rp="alias | g 'rustup ' | sed -E 's/^alias |$erp //g;s/=/\t/' | tr -d \' | g -v 'rp\t'"

egit="$(echo $i | sed 's/\//\\\//g')"
alias i="alias | sed -E 's/^alias |$egit //g;s/=/\t/' |  g '^i[^\tw]' | tr -d \'"

t() {
  alias | sed -E 's/^alias |\/usr\/bin\/|ctl //g;s/=/\t/' |
  rg ^t | rg -v 'tmux|touch|ssh|home' |
  tr -d \' |
  awk '{print substr($0,3,1) substr($0,1,2) substr($0,4)}' |
  sort |
  awk '{print substr($0,2,2) substr($0,1,1) substr($0,4)}'
}


#############
### CLANG ###
#############

alias gcc="use cc"
alias gccw="cc -Wall -Wextra -Wpedantic -Werror -Wconversion -Wuninitialized -Wundef -Wshadow -Wvla -Wcast-align -Wstrict-prototypes -Wmissing-declarations -Wstrict-overflow=5 -Wnull-dereference -Wlogical-op -Wpacked -Wpointer-arith -Wcast-qual -Wswitch-default -Wmissing-noreturn -Wredundant-decls -Wno-unused -Wno-unused-variable -Wno-unused-function -Wno-unused-parameter -Wno-sign-compare -Wno-format -Wno-type-limits -Wno-deprecated-declarations -Wfatal-errors "
alias clw='clang -Werror -Wextra -Wconversion -Wuninitialized -Wundef -Wshadow -Wvla -Wcast-align -Wstrict-prototypes -Wmissing-declarations -Wstrict-overflow -Wnull-dereference -Wpacked -Wpointer-arith -Wcast-qual -Wswitch-default -Wmissing-noreturn -Wredundant-decls -Wno-unused -Wno-unused-variable -Wno-unused-function -Wno-unused-parameter -Wno-sign-compare -Wno-format -Wno-type-limits -Wno-deprecated-declarations'
alias clang="use cl"
alias cl="/usr/bin/clang"
alias cinit="cp $CMD/data/.clang* ."

##########################
### CONFIG INDEPENDANT ###
##########################

alias dt="date"
alias ChkTeX='chktex'
alias qr="qrencode"
alias notif="dunstify"
alias dockerc="docker-compose"
alias wi="which"
alias xo="xournalpp"
alias y="yes"
alias fr="setxkbmap fr"
alias chmd="sudo chmod"
alias chw="sudo chown"
alias gpg-list="gpg --list-secret-keys --keyid-format=long"
alias cols="tput cols"
alias gpt="PS1='$ ' && PROMPT_COMMAND=''"
alias hd="head"
alias hour="date '+%H:%M:%S'"
alias dt="date"
alias use="echo use"
alias rand="openssl rand -base64 255"
alias path="echo $PATH"
alias cnt="wc -l"
alias xcnt="xargs cnt"
alias codex="code --install-extension"
alias lock="vlock --all"
alias vg="valgrind --track-origins=yes --show-error-list=yes --show-leak-kinds=all --leak-check=full"
alias cls="clear"
alias fix="stty sane"
alias zoom="xrandr --output DP-0 --scale 0.8x0.8"
alias dezoom="xrandr --output DP-0 --scale 1.5x1.5"

#####################################
#####################################
#####################################

alias xclip="use x"
alias x='/usr/bin/xclip -selection c'

alias rg="use g"
alias grep="rg"
alias ripgrep="rg"
alias g="$CARGO_HOME/bin/rg"
alias gv="g -v"
alias ge="g -e"
alias gve="g -ve"
alias gg="g --hidden"

alias sede="sed -E"

alias duf="du -h .  | g -ve '/.*/'"
alias duff="du -h .  | g -ve '/.*/.*/'"
alias dufff="du -h .  | g -ve '/.*/.*/.*/'"
alias duffff="du -h .  | g -ve '/.*/.*/.*/.*/'"
alias dufffff="du -h .  | g -ve '/.*/.*/.*/.*/.*/'"

alias codium="use uu"
alias vscodium="echo what is the difference with codium?"
alias uu="/usr/bin/codium --extensions-dir='$CODE_EXTS_PATH'"
alias code="/usr/bin/code --extensions-dir='$CODE_EXTS_PATH'"
alias u="bspc desktop -f neovim && uu ."

alias :wq="echo '🚬'"
alias :q="echo '🚬'"
alias q="echo '🚬'"
alias wq="echo '🚬'"

alias cup="p $CMD/src && mk release && pp"
alias cupd="p $CMD/src && mk debug && pp"

alias mk="/usr/bin/make"
alias make="use mk"
alias mn="/usr/bin/man"
alias man="use mn"

alias bp="s /sys/class/power_supply/BAT1/capacity"
alias mitapache="cp $CMD/data/LICENSE-MIT . && cp $CMD/data/LICENSE-APACHE ."
alias mit="cp $CMD/data/LICENSE-MIT ."
alias mvg="make valgrind"
alias vimsh="$DEV/vsh/main.out"
alias secret=". $FILES/.secret/vars"
alias z=". $CMD/sh/shellrc"
alias fda="fd --hidden --no-ignore"
alias ap="apps"
alias jql="jq -C  | less -R"
alias sr="sv README.md || sv docs/README.md"
alias cours="s $FILES/2a"
alias gr="setxkbmap gr"
alias ok=". ok"
alias ling="/home/b/.files/.data/local/share/gem/ruby/3.4.0/bin/github-linguist"
alias nt="numbat"
