#!/bin/bash

##############################################
########## ALIAS DEFINITION HELPERS ##########
##############################################

_check=

incr() {
        local var="$1"
        eval "$var=\$(( $var + 1 ))"
}

_wi() {
        /usr/bin/which "$1" 2>/dev/null || echo "echo unknown "
}

_sections=
_print_sections() { _al "$1" "printf '$_sections'"; }

_buff=
_flush() { _buff=; }
_sep() { _buff="$_buff\n"; }
_print() {
        _al "$1" "l && echo -e '$_buff'" !
        _sections="$_sections$1\t$2\n"
}

_buffappend() {
        _buff="$_buff$1\t$2\n"
}

[ -n "$_checked" ] && echo "" >"$LOGS/alias_names"

_al() {
        if [ "$2" = '-p' ]; then
                local dest="$3 $4"
                if [ -z "$5" ]; then
                        local comment="$4"
                else if [ "$5" != '!' ]; then
                        local comment="> $5"
                fi; fi

        else
                local dest="$2"
                if [ -z "$3" ]; then
                        local comment="$2"
                else if [ "$3" != '!' ]; then
                        local comment="> $3"
                fi; fi
        fi

        alias "$1"="$dest"

        if [ -n "$_check" ]; then

                s "$LOGS/alias_names" | /bin/awk '{print $1}' | /bin/grep -q "^$1$" && {
                        echo "$1 is defined twice"
                }
                echo "$1 $dest" >>"$LOGS/alias_names"
        fi

        if [ -n "$comment" ]; then
                _buffappend "$1" "$comment"
        fi
}

_banned=""

_ual() {
        local should_use="$1"
        shift
        for banned in $@; do
                _al "$banned" "echo use $should_use" !
                _banned="$_banned|$banned"
        done
}

_uall() {
        for banned in $@; do
                _al "$banned" "echo use alias for $banned" !
                _banned="$_banned|$banned"
        done
}

_dal() {
        if [ "$2" = '-p' ]; then
                local start=5
                local name="$4"
        else
                local start=3
                local name="$2"
        fi

        _arg() {
                if [ "${#1}" = '1' ]; then
                        printf '%s\n' "-$1"
                else
                        printf '%s\n' "--$1"
                fi
        }

        _abbr() { echo "${1:0:1}"; }

        _inner() {
                if [ "$2" = "-p" ]; then
                        local dest="$4"
                else
                        local dest="$2"
                fi

                if [ -n "$6" ]; then
                        dest="$dest $6"
                fi

                if [ "$2" = "-p" ]; then
                        _al "$1$5" -p "$3" "$dest" !
                else
                        _al "$1$5" "$dest" !
                fi
        }

        local argv=("${@:$start}")
        local n=${#argv[@]}
        local max=$((1 << n))

        local display_args=""

        for ((mask = 0; mask < max; mask++)); do
                local abbrs=""
                local args=""

                for ((idx = 0; idx < n; idx++)); do
                        if ((mask & (1 << idx))); then
                                continue
                        fi

                        local arg=${argv[idx]}

                        abbrs+="$(_abbr $arg)"
                        args+=" $(_arg $arg)"
                done

                _inner "$1" "$2" "$3" "$4" "$abbrs" "$args"
        done

        for ((idx = 0; idx < n; idx++)); do
                display_args="$display_args[${argv[idx]}] "
        done

        _buffappend "$1" "$name $display_args"
}

_s="$(_wi sudo)"

###########################
########## ALIAS ##########
###########################

unalias -a

_al all 'builtin alias'
_dal ad 'builtin unalias' a

_al aa "all | sed \"s/^alias //;s/='/\t/;s/'$//\""

cup="$(_wi make) -C $CMD/src --no-print-directory -j 50"
_al cup "$cup release"
_al cupc "$cup clean && $cup release"
_al cupd "$cup debug"

_al uz "builtin unalias -a && alias z='. /etc/bash.bashrc' && alias rb='. ~/.bashrc'"
_al raw "PS1='$ ' && PROMPT_COMMAND='' && uz"

##########################
########## ECHO ##########
##########################

_dal eh echo e # don't ual: on macos, echo is not echo
_al ehn printf
_al ehen printf
_al ret 'eh $?'

############################
########## PACMAN ##########
############################

if [ -f '/etc/arch-release' ] || [ -f '/etc/artix-release' ]; then
        _flush

        p="$(_wi yay)"
        _uall pacman paru yay

        _al paruu "$p" paru
        _al S -p "$p" '-S --needed --noconfirm'
        _al Ss -p "$p" '-Ss'
        _al Si -p "$p" '-Si'
        _al Sii -p "$p" '-Sii'
        _al R -p "$p" '-R --noconfirm'
        _al Q -p "$p" -Q
        _al G -p "$p" -G
        _al Qq -p "$p" -Qq
        _al Qd -p "$p" -Qd
        _al Qt -p "$p" -Qt
        _al Qent -p "$p" -Qent
        _al Qdt -p "$p" -Qdt
        _al Qdtq -p "$p" -Qdtq
        _al Rcns -p "$p" -Rcns
        _al Rdd -p "$p" -Rdd
        _al U "$p -Syyuu --devel --noconfirm && $p --devel --gendb -Y" 'update packages and completions'
        _al F -p "$p" -F
        _al Fy -p "$p" -Fy
        _al C "$p -Rcns \$($p -Qdtq) --noconfirm && yes | $p -Scc" 'remove unused + clear cache'

        m='/etc/pacman.d/mirrorlist'
        if [ -f '/etc/artix-release' ]; then
                _al M "rankmirrors $ETC/artix-mirrors | sudo tee $m && U"
        else if [ -f '/etc/arch-release' ]; then
                _al M "sudo reflector --latest 30 --sort rate --save $m --connection-timeout 20 --number 15 reflector && U"
        fi; fi

        _print pr paru
else if [ "$(uname)" = "Darwin" ]; then
        _flush

        _uall brew
        b="$(_wi brew)"
        _dal S -p "$b" install cask
        _al R -p "$b" uninstall
        _al Ss -p "$b" search
        _al Up -p "$b" update
        _al Ug -p "$b" upgrade
        _al U 'Up && Ug'
        _al Q -p "$b" list
        _al Qt -p "$b" 'list --installed-on-request'
        _al Qd -p "$b" 'list --installed-as-dependency'

        _print bw brew
fi; fi

#########################
########## BUN ##########
#########################

_flush

b="$BUN_INSTALL/bin/bun"
_ual b bun
_al ba -p "$b" add
_dal bi -p "$b" i g D
_dal bu -p "$b" update g
_al bur -p "$b" "upgrade && $b update -g"
_dal brm -p "$b" remove g
_al binit -p "$b" init
_al bc "rn *lock* && rn .next && rn node_modules && $b i && $b run build"

_sep

_al br -p "$b" run
_al bs 'br start'
_al bb 'br build'
_al bd 'br dev'
_al bf 'br fmt'

_sep

_al nextjs -p "$b" 'x create-next-app@latest --typescript --eslint --tailwind --app --turbopack  --src-dir --use-bun'

_sep

_uall bunx bx
_ual bk knip
_ual bl lint
_ual bp prettier
_al bk -p "$b" 'x knip'
_al bl -p "$b" 'x eslint'
_al bp -p "$b" 'x prettier -cw .'
_al bpp -p "$b" 'x pretier'
_al bcn -p "$b" 'x shadcn@latest add'

_print b bun

############################
########## PRISMA ##########
############################

_flush
_pam() { _al "pam$1" -p "$b x prisma migrate" "$2"; }

_pam r reset
_pam rf 'reset --force'
_pam v resolve
_pam s status
_pam d deploy
_pam m 'dev --name'

_print pam 'prisma migrate'

_sep

_pa() { _al "pa$1" -p "$b x prisma" "$2"; }

_pa o studio
_pa i init
_pa g generate
_pa s 'db seed'
_pa pl pull
_pa ph push
_pa v validate
_pa e version
_pa f format

_print pa prisma

###########################
########## CARGO ##########
###########################

_flush

c="$CARGO_HOME/bin/cargo"

_uall cargo

_al ck 'l && c yfaw-DR && c b &&  c f &&  c odaD && c t && c pf 100' 'all checks for ci'

_al co 'brave tarpaulin-report.html'

_al cy 'eh -e "\n#![warn(missing_docs,warnings,deprecated_safe,future_incompatible,keyword_idents,let_underscore,nonstandard_style,refining_impl_trait,rust_2018_compatibility,rust_2018_idioms,rust_2021_compatibility,rust_2024_compatibility,unused,clippy::all,clippy::pedantic,clippy::style,clippy::perf,clippy::complexity,clippy::correctness,clippy::restriction,clippy::nursery,clippy::cargo)]\n#![allow(clippy::single_call_fn,clippy::implicit_return,clippy::pattern_type_mismatch,clippy::blanket_clippy_restriction_lints,clippy::missing_trait_methods,clippy::question_mark_used,clippy::mod_module_files,clippy::module_name_repetitions,clippy::pub_with_shorthand,clippy::unseparated_literal_suffix,clippy::else_if_without_else)]\n"' 'all warnings for lib.rs'

_al cyx 'cy | x'

_al ct 'printf $(s $CMD/secret/cratesio.txt) | x'

_print ccc cargo

############################
########## RUSTUP ##########
############################

_flush

_ual Rc rustc
_dal Rc "$(_wi rustc)" print W
_al Rct 'rcp target-list'

r="$(_wi rustup)"

_al rpt -p "$r" toolchain
_dal rptl -p "$r" 'toolchain list' installed

_al rptu -p "$r" 'toolchain uninstall'
_al rptus -p "$r" 'toolchain uninstall stable'
_al rptun -p "$r" 'toolchain uninstall nightly'

_al rpti -p "$r" 'toolchain install'
_al rptis -p "$r" 'toolchain install stable'
_al rptin -p "$r" 'toolchain install nightly'

_sep

_al rpg -p "$r" target
_al rpga -p "$r" 'target add'

_sep

_al rpc -p "$r" component
_al rpca -p "$r" 'component add'
_dal rpcl -p "$r" 'component list' installed
_al rpcr -p "$r" 'component remove'

_sep

_al rpd -p "$r" default
_al rpu -p "$r" update
_al rpv -p "$r" --version
_dal rpo -p "$r" doc std

_sep

_ual r1 rtr
_ual rf rfull
_al r0 'export RUST_BACKTRACE=0'
_al r1 'export RUST_BACKTRACE=1'
_al rf 'export RUST_BACKTRACE=full'

_print rp rust

#########################
########## IWD ##########
#########################

_flush

dw="$(_wi sudo) $(_wi iwctl)"
dw0="$dw station wlan0"

_uall iw0 dw0
_ual dwr iwgh iwr dwgh

_al dwc -p "$dw0" connect
_al dwd -p "$dw0" disconnect
_al dwg -p "$dw0" get-networks
_al dws -p "$dw0" scan

_sep

_al dwl -p "$dw" 'known-networks list'
_al dwk -p "$dw" known-networks

_sep

_al dwr 'dws; while :; do l; dwg; sleep 1; done'

_print iw iwctl

#########################
########## GIT ##########
#########################

_flush

_al ififo 'export GIT_ASKPASS=read-fifo'
_al ilon 'i lo=n'
_al igh 'slp 1 && i phO HEAD:refs/for/master'
_al ighw 'i phO HEAD:refs/for/master%wip'
_al iyfa 'i yfrw ../*.diff'
_al ilg 'i l | rg -A5'
_al ica 'i canrS'
_al ifh 'i phf'

_al irslm 'i rshm && i pl'
_al irslmm 'i rshmm && i pl'

_al iws 'p $(iwss)'
_al iwc 'i wl | g HEAD | w1 | while read wt; do iwr $wt; done'
_al ickg '. ickg'
_al iwn '. iwn'

_sep

_al iswh 'i sw $(i br --color | fzf --ansi | wnf)'
_al irbi 'i rbi $(i lo | fzf  --no-sort | w1)'
_al ilsw 'i lo | fzf | w1 | i swc zzz'

_sep

_al ig git-graph

_sep

_al h "$(_wi gh)"
_ual h gh ih

_al hr 'h repo'
_al hp 'h pr'
_al ha 'h auth'
_al hai 'ha login'
_al hao 'ha logout'
_al hag 'ha setup-git'

_sep

_al hcr 'hr create'
_al hcl 'hr clone'
_al hd 'hr set-default'

_sep

_al hrv 'hr view'
_al hpv 'hp view'
_al hv 'hpv || hrv'

_al hrw 'hrv -w'
_al hpw 'hpv -w'
_al hw 'hpw || hrw'

_ual i git
_print iz git

#############################
########## SYSTEMD ##########
#############################

_flush

_ual ty systemctl

if [ "$(uname)" = "Darwin" ]; then
        _al tyy "$(_wi brew) services"
        _al ty "$(_wi sudo) $(_wi brew) services"
else
        _dal tyy "$(_wi systemctl)" user
        _al ty "/usr/bin//bin/sudo $(_wi systemctl)" user
fi
_al tyu 'ty list-unit-files'

_ual tj journalctl
_dal tjj "$(_wi journalctl)" user
_al tj '/bin/sudo tjj'
_al tje 'tj -xeu'
_al tjje 'tjj -xeu'
_al tjjue 'tjju -xeu'

_sep

_uall tz
tz="$(_wi systemd-analyze)"
_al tzb -p "$tz" "blame"
_al tzp -p "$tz" "plot > del.svg"
_al tzc -p "$tz" "critical-chain"

_sep

_ual tb reboot
_ual tw shutdown
_al tu 'ty suspend'

if [ "$(uname)" = 'Linux' ]; then
        _al tw "$_s $(_wi shutdown) -P now -h"
else
        _al tw "$_s $(_wi shutdown) -h now"
fi

_dal tb "/bin/sudo $(_wi reboot)" force

_sep

_ual tr restart
_ual ta start
_ual tt status
_ual to stop
_ual td disable
_ual te enable

_ctl_def() {
        if [ -z "$3" ]; then
                local c=ty
                local j=tje
        else
                local c=tyyu
                local j=tjjue
        fi
        if [ -z "$2" ]; then
                arg=""
        else
                arg=" $2"
        fi

        [ -n "$1" ] && local end=!

        _al "ta$1" "$c start$arg" "$end"
        _al "ts$1" "$c restart$arg" "$end"
        _al "tt$1" "$c status$arg" "$end"
        _al "to$1" "$c stop$arg" "$end"
        _al "te$1" "$c enable$arg" "$end"
        _al "td$1" "$c disable$arg" "$end"

        [ -n "$1" ] && _al "tj$1" "$j$arg" "$end"
}

_ctl_def

_sep

_ctl_def iw iwd
_ctl_def rd systemd-resolved
_ctl_def net 'iwd systemd-resolved'
_ctl_def sql postgresql
_ctl_def d docker
_ctl_def p podman
_ctl_def au 'pipewire.socket pipewire-pulse pipewire-pulse.socket wireplumber' u
_ctl_def aa 'pipewire.socket pipewire-pulse pipewire-pulse.socket pipewire-media-session' u

_print t systemd

############################
########## PYTHON ##########
############################

_flush

_ual y py
_al y python3
_al yi 'py -i'
_al yp 'pym ensurepip && pym pip install --upgrade pip'
_al ya 'pyp && pym pip install rich yapf pyright'
_al yr 'mdl python/python/3.13.5 && python'
_al ym 'py -m'
_al yu 'pym unittest'

_ual srv serve server serv
_al srv 'srvr -b localhost'
_al srvr 'ym http.server'

_al vn 'uv venv'
_al va '. .venv/bin/activate'
_al vd 'deactivate'

_print yy python

#########################
########## SEE ##########
#########################

_ual s cat l
_ual v bat ll eza

_al svv "$(_wi eza) -lA --git"

_al ls l
_al la l
_al lla ll
_al llag ll

_al sr 'v README.md || v docs/README.md || v README || v docs/README'

_al gcv 'gc v'
_al gk 'gc keymaps.lua'

_ual rd readlink pwdf
_al rd "$(_wi readlink) -f"
_al px 'eh -n $(pwd) | x'

#########################
########## GUI ##########
#########################

########## ALACRITTY

_al alcg 'alacritty msg config'
_al resize "alacritty msg config 'font.size = 6'"

########## OPEN

_ual o xdg-open

if [ $(uname) = "Darwin" ]; then
        _al o open
else
        _ual o open
fi

_al ok '. drop o'
_al ducl 'dunstctl close-all'

######## XCLIP

_ual x xclip pbpaste pbcopy
_al x "$XCOPY"
_al xo "$XPASTE"
_al clipm clipcat-menu

######## CODIUM

_ual uimm codium
_al vscodium 'eh what is the difference with codium?'
_al uimm "/bin/codium --extensions-dir='$CODE_EXTS_PATH'"
_al code "/bin/code --extensions-dir='$CODE_EXTS_PATH'"
_al uim 'bspc desktop -f neovim && uimm .'

######## XRANDR

_ual xr xrandr
_al xr /bin/xrandr
_al xr0 'xr --output $(xr | gw connected | hd -1 | w1)'
_al zoom 'xr0 --scale 0.8x0.8'
_al dezoom 'xr0 --scale 1.5x1.5'

#############################
########## NETWORK ##########
#############################

_al wb '. drop wb'
_al ws 'wb https://synapses.telecom-paris.fr/login?type=Shib'
_al we 'wb https://ecampus.paris-saclay.fr/my/'

_al pi 'while :; do ping -c 3 std.rs; sleep 1; done'

_al rpi "ssh $_RPI_UNAME@$_RPI_IP"
_al mssh "ssh mad@mad-ssh.rezel.net -J twebber-23@ssh.enst.fr"
_ual tesh tessh
_al tesh "ssh jet@137.194.13.203 -J twebber-23@ssh.enst.fr"
_al pssh 'ssh twebber-23@perso-twebber-23.lxc.enst.fr -J twebber-23@ssh.enst.fr'
_al gssh "s ~/.ssh/id_ed25519.pub | x && s ~/.ssh/id_ed25519.pub"
_al enst 'ssh twebber-23@ssh.enst.fr'

_ual rl curl
_dal rl "$(_wi curl)" L O i progress-bar X H
_al get 'rlX GET'
_al post 'rlX POST'

###########################
########## PUSHD ##########
###########################

_ual p cd
_ual j pop pp
_al p '. pdd'
_al j 'popd >/dev/null'
_al pc 'dirs -c'
_al pl 'dirs -v'
_al k 'p ..'
_al kk 'k && k'
_al kkk 'k && k && k'
_al kkkk 'k && k && k && k'
_al kkkkk 'k && k && k && k && k'

_al src 'p src'

_gt() {
        _al "$1" "l && p $2 && v"
}

_ual 'ocf or xcf' cf
_gt ap "$APPS"
_gt ocf "$OCFG"
_gt xcf "$XDG_CONFIG_HOME"
_gt cmd "$CMD"
_gt data "$DATA"
_gt log "$LOGS"
_gt dot "$DOT"
_gt del "$WASTE"
_gt etc "$ETC"
_gt pf "$FILES"
_gt ph "$HOME"
_gt work "$WORK"
_gt build "$WORK"
_gt good "$BUILD/good"
_gt auto "$BUILD/good/auto-build"
_gt rt "$BUILD/good/runtime"

_ual st cours
_gt st "$STUDY"

_gt blob "$BLOB"
_gt sav "$BLOB/save"

_gtd() {
        _gt "$1" "$DEV/$2"
}

_gtd dev
_gtd pemail email
_gtd phtml html-filter
_gtd prdj random-json
_gtd prda random-data
_gtd jc jet-centre
_gtd crs crs
_gtd crsu 'crs/crs-tui'
_gtd crsb 'crs/crs-backend'
_gtd crss 'crs/server'
_gtd pmail mailbox
_gtd mdv md-viewer
_gtd pars c-parser
_gtd perso personal-website
_gtd sw showcase-website
_gtd vsh vimsh
_gtd words words
_gtd TOdo test-hokla-aphp-py-tom-webber

_al gd 'p $DEV && p $(fd --type d -d 1 | fzf)'

for l in c r y g; do
        _gtd "pdel$l" ".$l"/
        _al "del$l" "pdel$l && e ."
done

##########################
########## EDIT ##########
##########################

_al hx helix

_ual e vi vim nvim
_ual ew bsp bspwmrc
_ual eX sxhkdrc

_al se "/bin/sudo $EDITOR"
_al rx 'pkill -USR1 -x sxhkd'

_ual rn rm rms
_al rmm /bin/rm
_al rmrf 'rmm -rf'

_ge() {
        [ "$1" != "w" ] && _al "s$1" "gc $2"
        _al "e$1" "ed $2"
}

_ge s saved.txt
_ge a aliases
_ge k keymaps
_ge sl statusline
_ge fn functions
_ge ss settings
_ge col colours
_ge y lazyconfig
_ge rc shellrc
_ge lsp lsp
_ge p profile
_ge x sxhkdrc
_ge w bspwmrc

_ual n touch

_al eb 'e ~/.bashrc'
_al rb '. ~/.bashrc'
_al rc '. $CMD/sh/shellrc'

_al q 'ehe "\033[32m  \033[0m"'
_al wq q
_al :wq q
_al :q q

###########################
########## CLANG ##########
###########################

_ual cc gcc
_al gccw 'cc -Wall -Wextra -Wpedantic -Werror -Wconversion -Wuninitialized -Wundef -Wshadow -Wvla -Wcast-align -Wstrict-prototypes -Wmissing-declarations -Wstrict-overflow=5 -Wnull-dereference -Wlogical-op -Wpacked -Wpointer-arith -Wcast-qual -Wswitch-default -Wmissing-noreturn -Wredundant-decls -Wno-unused -Wno-unused-variable -Wno-unused-function -Wno-unused-parameter -Wno-sign-compare -Wno-format -Wno-type-limits -Wno-deprecated-declarations -Wfatal-errors '

if [ "$DEVICE" != "v" ]; then
        _ual cl clang
        _ual clp clang++
        _ual clf clang-format
        #         _al cl "$(_wi clang)"
        _dal clp "$(_wi clang++)" version
        _al clf "$(_wi clang-format)"
else
        #         _al cl clang
        _dal clp clang++ version
        _dal clf clang-format i
fi
_al clw 'cl -Werror -Wextra -Wconversion -Wuninitialized -Wundef -Wshadow -Wvla -Wcast-align -Wstrict-prototypes -Wmissing-declarations -Wstrict-overflow -Wnull-dereference -Wpacked -Wpointer-arith -Wcast-qual -Wswitch-default -Wmissing-noreturn -Wredundant-decls -Wno-unused -Wno-unused-variable -Wno-unused-function -Wno-unused-parameter -Wno-sign-compare -Wno-format -Wno-type-limits -Wno-deprecated-declarations'

_al cinit "cp $CMD/data/.clang* ."
_al vg 'valgrind --track-origins=yes --show-error-list=yes --show-leak-kinds=all --leak-check=full'

##############################
########## KEYBOARD ##########
##############################

_ual fr setxkbmap
_ual frr loadkeys
s=/bin/setxkbmap
_al fr "$s fr"
_al frr '/bin/sudo /bin/loadkeys fr-latin1'
_al grr "$s gr"
_al gr "grr && read x; fr; eh \$x | x; eh \$x"

############################
########## RIGHTS ##########
############################

_ual chd chmod
_ual chw chown

_dal chd "$(_wi chmod)" R
_al chdx 'chd +x'
_dal chds '/bin/sudo chd' R
_al chdsx '/bin/sudo chdx'

_al chw "$(_wi chown)"
_dal chwr "chw root:root" R
_dal chwb "chw $USER:$USER" R
_al chws '/bin/sudo chw'
_dal chwsr '/bin/sudo chwr' R
_dal chwsb '/bin/sudo chwb' R

###########################
########## PIPES ##########
###########################

_ual xg xargs
_al xg "$(_wi xargs)"
_al cnt 'wc -l'
_al xcnt 'xg wc -l'
_al xgi 'xg -I'
_al xgid 'xg -I.'
_al xgib 'xg -I{}'

_ual hd head
_al hd "$(_wi head)"
_al hn "hd -n"
for x in $(seq 0 9); do
        _al "h$x" "hd -n $x"
done

_ual tl tail
_al tl /usr/bin/tail

_ual so sort sn
_dal so /usr/bin/sort n

_ual u uniq
_dal u /usr/bin/uniq c d

_al d sed
_al de 'd -E'
_al less 'less -R'

_al jql 'jq -C  | less -R'

_al cpr 'cp -r'

########################
########## RG ##########
########################

_ual g grep ripgrep

_flush

_al g rg

# _al g '_dal g "$CARGO_HOME/bin/rg" N U i v w hidden no-ignore o e q'
_al gm 'mrep'

_al gs "gv '^\$'" 'gv ^$'

_print ghh rg

#########################
########## AWK ##########
#########################

_flush

_ual a awk
_al a '/usr/bin/awk '
_al af 'a -F'
_al aw "'{print \$2}'"

for ((i = 0; i <= 30; i++)); do
        _al "aa$i" "'{print \$$i}'"
        _al "a$i" "a aa$i"
done

_al al "a '{print length, \$1}'"
_al all 'a aal'
_al aal "'{print length}'"
_al aanf "'{print \$NF}'"
_al anf 'a aanf'
_al aarev "'{print \$2, \$1}'"
_al arev "a aarev"
_al aadup "'{print \$0, \$0}'"
_al adup 'a aadup'

_print aaa awk

###########################
########## POWER ##########
###########################

_al pws '/bin/sudo cpupower frequency-set -g powersave'
_al pwp '/bin/sudo cpupower frequency-set -g performance'
_al pww 's /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor'

#############################
########## PROCESS ##########
#############################

_flush

_al psa 'ps -ax | g '

_kal() {
        _al "k$1" "killapp $2"
}

_kal e beeper
_kal v brave
_kal d dunst
_kal D Discord
_kal c clipcat
_kal r reflector
_kal o code
_kal u codium
_kal x sxhkd
_kal X Xorg
_kal hf w bspwm
_kal g gotop
_kal a adb
_kal p paru

_al bt btop

_al bare 'tonet; toau; tosql; to systemd-timesyncd systemd-journald systemd-journald.socket systemd-journald-dev-log.socket polkit; kr; kv; kd; kp; kc; kD; ku; ko; kg; ka; ke'

_al bgd 'bg && disown'
_al psg pgrep

_al kbg 'pkill -u "$USER" -x bash -P 1'

_print kk kill

##########################
########## TMUX ##########
##########################

_flush

x=$(_wi tmux -f "$OCFG/tmux.conf")

_x() {
        _al "x$1" -p "$x" "$2"
}

_ual x tmux

_x x
_x a 'a -t'
_x l ls
_x n 'new-session -s'
_x k 'kill-session -t'

_al xr -p "$x" "source-file $OCFG/tmux.conf"

_al x0 'xe 0'
_al x1 'xe 1'
_al x2 'xe 2'
_al xs "xa \$(xl | fzf | w -F':' ww1)"
_al xh 'v $OCFG/tmux.conf'

_print xxx tmux

#####################################

_al wi '. wi'
_ual wi which whereis
_al path 'eh $PATH'

_al zh "s $SECRET/bash_history"
_al zhh "zh | gv '^#'"
_al zhvban "zhh | gv '$_banned'"
_al zhf 'zh | fzf'

_dal de declare f

_al mboot 'm /dev/nvme0n1p1 /boot'
_ual mkcp mkinitcpio
_al mkcp '/bin/sudo /bin/mkinitcpio -P'

_ual m mnt mount make man mn
_al mls "make -qp | awk -F':' '/^[a-zA-Z0-9][^$#\/\t=]*:([^=]|$)/ {split(\$1,A,/ /);for(i in A)print A[i]}' | sort -u"

_al ti time
_al hf "$(_wi hyperfine)"
_ual hf hyperfine

_al dt "$(_wi date)"
_ual dt date
_al dtl 'ehe "\033[35m[$(dt "+%Y/%m/%d %H:%M:%S:%N")]\033[0m"'
_al hour "dt '+%H:%M:%S'"

_al mitapache "cp $CMD/data/LICENSE-MIT . && cp $CMD/data/LICENSE-APACHE ."
_al mit "cp $CMD/data/LICENSE-MIT ."
_al vimsh "$DEV/vsh/main.out"
_al secret ". $SECRET/vars"
_al ling "$XDG_SHARE_HOME/gem/ruby/3.4.0/bin/github-linguist"

_al ChkTeX chktex
_al qr qrencode
_al notif dunstify
_al gpg-list 'gpg --list-secret-keys --keyid-format=long'
_al cols 'tput cols'
_al rand 'openssl rand -base64 255'
_al codex 'code --install-extension'
_al fix 'stty sane; builtin cd; echo $HOME > $LOGS/last_location.log; printf "\033[0m"'
_ual l cls clear
_al l 'printf "\033c"'
_al nt numbat
_al tf trufflehog
_al qa qalc

wasted=".config .config/* .local .local/* .pki .pki/* .cache .cache/*"
_al clean "h; v $wasted; rn $wasted"

_al wr 'curl wttr.in'

_al slp sleep

_al alac "$(_wi open) -n -a alacritty"

_ual rdj random-json
_al rdj "$(_wi random-json)"

_ual sra sort-rust-array
_al sra "$CARGO_HOME/bin/sort-rust-array"

_al ltx pdflatex

_al gx2 "gx | uc | gv '^\s*1'"

_al adbl 'adb shell pm list packages'
_al adbu 'adb uninstall --user 0'
_al adbd 'adb shell pm disable-user --user 0'

_ual ft floaterm
_ual jp joplin
_al jp "$(_wi joplin) --profile $OCFG/joplin"

_al mdl 'module load'

_al minit 'yabai & skhd & disown'
_al np 'PAGER= '
_al longrand 'echo $(((RANDOM << 16) | RANDOM))'
_al rw rlwrap
_al tilde 'echo \~'
_ual ds dust
_al ds "$(_wi dust)"
_al dsx 'ds -X .snapshot'
_al ds1 'ds -d 1'
_dal ob objdump T
_al zj 'zellij --config $XDG_CONFIG_HOME/zellij/config.kdl'
_al gitignore "eh '*' > .gitignore"
_al loop '. loop '
_al wpad '/bin/sudo wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf'
_al rnf 'fd --type d | xgid -P 50 rm -rf . &>/dev/null'
_al np '. np'
_al w while
_al ed '$CMD/sh/ed'

_print other done

#####################################

_print_sections '??'
