#!/bin/bash

/bin/date >/tmp/log

. ~/.bashrc

la BASH_PROFILE

if [ -z "$TMUX" ]; then
        if [ "$(tty | tr -c '1' '.' | tr -d '.')" = "1" ]; then
                wpad &>>/tmp/log &
                sudo dhcpcd &>>/tmp/log &
                exec startx
        else
                sudo rmmod pcspkr &>>/tmp/log
                sudo loadkeys fr-latin1 &>>/tmp/log
        fi
fi
