#!/bin/sh

case "$1" in
"") echo "Missing argument" ;;
"up")
        brightnessctl s 10+
        ;;
"down")
        brightnessctl s 10-
        ;;
esac

notify-send -u low -t 500 "☀️$(brightnessctl g)%" -a center -h "string:x-dunst-stack-tag:stacked"
