#!/bin/sh

printf 'Name: '
read -r DEVICE </dev/tty

printf 'Files location (absolute path, ~ for $HOME): '
read -r FILES </dev/tty

if [ "$(echo "$FILES" | cut -c1-1)" = "~" ]; then
	FILES="$(echo "$FILES" | cut -c2-)"
	FILES="$HOME/$FILES"
fi

mv ~/.vars ~/.vars.old

printf '
export DEVICE=%s
export FILES=%s
' "$DEVICE" "$FILES" >~/.vars

mv ~/.bashrc ~/.bashrc.old

printf '#!/bin/sh

. "$HOME/.vars"

. "$FILES/dotfiles/cmd/sh/shellrc"
' >~/.bashrc

mv ~/.profile ~/.profile.old

printf '#!/bin/sh

. "$HOME/vars"

. "$FILES/dotfiles/cmd/sh/profile"
' >~/.profile

mkdir -p "$FILES"
cd "$FILES" || (
	printf "Access denied: failed to creates FILES folder"
	exit
)
git clone https://github.com/t-webber/dotfiles
./dotfiles/etc/link.sh

. "$HOME/.bashrc"
