#!/bin/sh

in="$1"

set -euo pipefail

edi() {
        exec $EDITOR "$1"
}
export -f edi

last() {
        l "$1" | tr '/' '\n' | rg -v '$\s*^' | tail -1
}

### NO ARGUMENT ###

if [ -z $in ]; then
        edi .
fi

### A FILE HERE ###

if [ -e "$in" ]; then
        edi "$in"
fi

### SEARCH FOR A FILE ###

case $in in
*/*) : ;;
*)
        if [ "$PWD" = "/" ]; then
                here="/var/empty"
        else
                here="."
        fi
        for folder in "$here" $CMD/src $CMD $DOT $HOME /etc /; do
                count=$(f E etc "$in" $folder | wc -l)
                if [ "$count" = 1 ]; then
                        edi "$(f E etc "$in" $folder)"
                fi
                if [ "$count" != 0 ]; then
                        f E etc "$in" $folder | fzf | x .n1 bash -c 'edi "."'
                        exit 0
                fi
        done
        ;;
esac

### A PATH ###

path=""
oldIFS=$IFS
IFS=/
for part in $in; do
        path="$path.*$part.*/"
done
IFS=$oldIFS
path="${path%?}"
la $path
count="$(f Hf "$path" | wc -l)"
if [ "$count" = 0 ]; then
        le $path: no such file or directory
        exit 1
fi
if [ "$count" = 1 ]; then
        edi "$(f | gg "$path")"
fi
f Hf "$path" | fzf --tac --query "$in" | x .n1 bash -c 'edi "."'
