#!/bin/sh

sxhkd & #>/home/b/.files/.data/logs/sxhkd.log 2>&1 &

setxkbmap fr &

xmodmap -e "clear Mod5"
xmodmap -e "add Mod3 = ISO_Level3_Shift"
# xrandr --output eDP-1 --scale 1.5x1.5

dunst &    #>/home/b/.files/.data/logs/dunst.log 2>&1 &
clipcatd & # >/home/b/.files/.data/logs/clipcatd.log 2>&1 &
