#!/bin/bash

set -euo pipefail

rg -N "$1" "$WORK/.cache/mod-all.txt"

{
        cd "$WORK/.cache" &&
                $(which mgrep) | awk -F'[() ]' '{print $2, $1}' >temp.txt &&
                mv temp.txt mod-all.txt
} &
