#!/bin/sh

_inner() {
        ps -eo user,%mem,rss --sort=-%mem --no-headers | awk '{per[$1]+=$2; mem[$1]+=$3} END { for (u in per)
             printf "%-15s %7.2f%% %5.2f GB\n", u, per[u], mem[u]/1024/1024
        }' | sort -k2 -nr | head
}

if [ -n "$1" ]; then
        while :; do
                printf "\033c"
                date
                _inner
                sleep 1
        done
else
        _inner
fi
