#!/bin/bash

if [ "$(uname)" = "Darwin" ]; then
        command -v nvm >/dev/null || {
                . $NVM_DIR/nvm.sh
                nvm use 24
        }
        p=$(_wi claude)
        nb=$($p mcp list | g _ Connected$ | cnt | tr -d ' \n')
        if [ "$nb" != "4" ]; then
                le Mcp not connected
        fi
else
        p="$(_wi copilot) --model gpt-5-mini --effort high"
fi

if [ "$1" = "resume" ]; then
        $p --resume $2
else
        $p
fi
