#!/bin/sh

sleep 5

tanet
taau

sd rmm "$FILES/.waste"
mkdir -p "$FILES/.waste"

while ! sd iwctl station wlan0 show | g -q ' connected'; do
	sleep 10
done

sd reflector --latest 30 --sort rate --save /etc/pacman.d/mirrorlist --connection-timeout 20 --number 15 &

bur &

if [ -f "/etc/arch-release" ]; then
	U &
	Fy &
	C &
fi

ru &
sd pkgfile --update &
"$ETC/link.sh"

wait
