#!/bin/sh

[ -z "$FILES" ] && export FILES="$HOME/.files"
[ -f "$FILES/.secret/vars" ] && . "$FILES/.secret/vars" >/dev/null
[ -z "$WASTE" ] && export WASTE="$FILES/.waste"
[ -z "$EDITOR" ] && export EDITOR="$(which nvim)"
[ -z "$XCOPY" ] && export XCOPY="$(which xclip) -selection c"
[ -z "$XPASTE" ] && export XPASTE="$XCOPY -o"

export DATA="$FILES/.data"
[ "$DEVICE" = "acer" ] && export XAUTHORITY="$DATA/Xauthority"

#############################
# custom location variables #
#############################

export DOT="$FILES/dotfiles"
export CMD="$DOT/cmd"
export XCFG="$DOT/xdgconfig"
export ETC="$DOT/etc"
export APPS="$FILES/.apps"
export DEV="$FILES/.dev"
export LOGS="$DATA/logs"
export SLOGS="$DATA/logs/start"
export SECRET="$FILES/.secret"
export STUDY="$FILES/.study"
export OCFG="$DOT/otherconfig"

#############################
# global location variables #
#############################

export XDG_CONFIG_HOME="$XCFG"
export XDG_DATA_HOME="$DATA/local/share"
export XDG_CACHE_HOME="$DATA/local/cache"
export XDG_STATE_HOME="$DATA/local/state"

###########################
# apps location variables #
###########################

export NPM_CONFIG_USERCONFIG="$OCFG/npm/config"
export NPM_CONFIG_CACHE="$OCFG/npm/cache"
export INPUTRC="$OCFG/inputrc"
export ANDROID_AVD_HOME=$OCFG/android-avd

export IPYTHONDIR="$DATA/ipython"
export SAGE_ROOT="$DATA/sage_root"
export WGETRC="$DATA/wget-hsts"
export DOT_SAGE="$DATA/sage_dot"
export GNUPGHOME="$DATA/gnupg"
export NODE_REPL_HISTORY="$DATA/repl/node_repl_history"
export TS_NODE_HISTORY="$DATA/repl/ts_node_repl_history"
export PYTHON_HISTORY="$DATA/repl/python_history"
export BUN_INSTALL="$DATA/bun"
export CARGO_HOME="$DATA/cargo"
export RUSTUP_HOME="$DATA/rustup"
export NVM_DIR="$DATA/nvm"
export GH_BINPATH="$DATA/git/gh"
export GEM_HOME="$DATA/gem/install"
export GEM_PATH="$DATA/gem/install"
export GEM_SPEC_CACHE="$DATA/gem/specs"
export CODE_EXTS_PATH="$DATA/code-extensions"
export GOROOT="$DATA/go/root"
export GOTOOLDIR="$DATA/go/tooldir"
export GOHOME="$DATA/go/home"
export GOPATH="$DATA/go/path"
export ANDROID_HOME=/opt/android-sdk/

export RUST_SRC="$CARGO_HOME/registry/src/"

####################
# global variables #
####################

export CC="cc"

if [ -f "/etc/arch-release" ]; then
        export DEBUGINFOD_URLS='https://debuginfod.archlinux.org/'
fi

export GPG_TTY="$(tty)"
export VCPKG_ROOT="$APPS/vcpkg"

export LC_ALL=en_GB.UTF-8
export LANG=en_GB.UTF-8

PATH=""
PATH+=":/bin"
PATH+=":/sbin"
PATH+=":/usr/bin"
PATH+=":/opt/homebrew/bin/"
PATH+=":$CMD/sh"
PATH+=":$CMD/bin"
PATH+=":$CARGO_HOME/bin"
PATH+=":$BUN_INSTALL/bin"
PATH+=":$GOROOT/bin"
PATH+=":$GOPATH/bin"
PATH+=":$APPS/flutter/bin"
PATH+=":$ANDROID_HOME/cmdline-tools/latest/bin"
export PATH

#########################
# rebuild changed utils #
#########################

[ -z "$1" ] && $(which make) -C "$CMD/src" --no-print-directory release &
disown 2>/dev/null # ignore output: not found if ran and not sourced

###########
# history #
###########

export HISTSIZE=4294967295
export HISTFILESIZE=4294967295
export HISTFILE="$SECRET/bash_history"
export HISTTIMEFORMAT='%F-%H-%M-%S '
export HISTCONTROL=ignoredups

shopt -s histappend

########################
# reload last location #
########################

export LAST_LOCATION_FILE="$LOGS/last_location.log"
n "$LAST_LOCATION_FILE"
builtin pushd "$(<$LAST_LOCATION_FILE)" >/dev/null # ignore output: not found if ran and not sourced

command_not_found_handle() { echo -e "\033[31mCommand not found: \033[32m$1\033[31m.\033[0m" >&2; }

prompt() {
        pwd >"$LAST_LOCATION_FILE"
        history -a
}

export PROMPT_COMMAND=prompt

#######
# PS1 #
#######

if [ "$(whoami)" = "root" ]; then
        export PS1='#$(ps1)'
else
        export PS1='$(ps1)'
fi

#############
# man pages #
#############

export MANSECT=3:2:1:8:5:4:9

export LESS="-R"
export MANPAGER='less -P "man"'

export LESS_TERMCAP_mb=$'\E[1;31m' # begin blinking
export LESS_TERMCAP_md=$'\E[1;35m' # begin bold
export LESS_TERMCAP_me=$'\E[0m'    # end mode
export LESS_TERMCAP_se=$'\E[0m'    # end standout-mode
export LESS_TERMCAP_so=$'\E[1;33m' # begin standout-mode
export LESS_TERMCAP_ue=$'\E[0m'    # end underline
export LESS_TERMCAP_us=$'\E[1;32m' # begin underline

##################
# other settings #
##################

umask 077 # default permissions on file are w/o perms to go

################
# load aliases #
################

[ -z "$1" ] && {
        . "$CMD/sh/aliases"
}
