#!/bin/sh

if [ "$(uname)" = "Darwin" ]; then

        export CC=/opt/homebrew/bin/gcc-15
        export XCOPY=/usr/bin/pbcopy
        export XPASTE=/usr/bin/pbpaste
        export DEVICE=mac

else

        export CC=/bin/gcc
        export XCOPY='/bin/xclip -selection c'
        export XPASTE="$XCOPY -o"

        if [ -f '/sys/class/power_supply/BAT1/capacity' ]; then
                export DEVICE=acer
        else
                export DEVICE=??
        fi

fi

#################################
### custom location variables ###
#################################

[ -z "$FILES" ] && export FILES="$HOME/.files"
export DATA="$FILES/.data"
export WASTE="$FILES/.waste"
export DOT="$FILES/dotfiles"
export CMD="$DOT/cmd"
export SH="$CMD/sh"
export XCFG="$DOT/xdgconfig"
export ETC="$DOT/etc"
export APPS="$FILES/.apps"
export DEV="$FILES/.dev"
export LOGS="$DATA/logs"
export SLOGS="$DATA/logs/start"
export SECRET="$FILES/.secret"
export STUDY="$FILES/.study"
export OCFG="$DOT/otherconfig"
export BIN="$FILES/.bin"
export BLOB="$FILES/.blob"
export WORK="$FILES/.work"

#################################
### global location variables ###
#################################

export XDG_CONFIG_HOME="$XCFG"
export XDG_DATA_HOME="$DATA/local/share"
export XDG_CACHE_HOME="$DATA/local/cache"
export XDG_STATE_HOME="$DATA/local/state"

###############################
### apps location variables ###
###############################

export NPM_CONFIG_USERCONFIG="$OCFG/npm/config"
export NPM_CONFIG_CACHE="$OCFG/npm/cache"
export INPUTRC="$OCFG/inputrc"
export ANDROID_AVD_HOME=$OCFG/android-avd

[ "$DEVICE" = "acer" ] && export XAUTHORITY="$DATA/Xauthority"
export IPYTHONDIR="$DATA/ipython"
export SAGE_ROOT="$DATA/sage_root"
export WGETRC="$DATA/wget-hsts"
export DOT_SAGE="$DATA/sage_dot"
export GNUPGHOME="$DATA/gnupg"
export NODE_REPL_HISTORY="$DATA/repl/node_repl_history"
export TS_NODE_HISTORY="$DATA/repl/ts_node_repl_history"
export PYTHON_HISTORY="$DATA/repl/python_history"
/bin/mkdir -p $DATA/repl
export BUN_INSTALL="$DATA/bun"
export CARGO_HOME="$DATA/cargo"
export NVM_DIR="$DATA/nvm"
export GH_BINPATH="$DATA/git/gh"
export GEM_HOME="$DATA/gem/install"
export GEM_PATH="$DATA/gem/install"
export GEM_SPEC_CACHE="$DATA/gem/specs"
export CODE_EXTS_PATH="$DATA/code-extensions"
export GOROOT="$DATA/go/root"
export GOTOOLDIR="$DATA/go/tooldir"
export GOHOME="$DATA/go/home"
export GOPATH="$DATA/go/path"
export ANDROID_HOME=/opt/android-sdk/

########################
### global variables ###
########################

[ -f "$SECRET/vars" ] && . "$SECRET/vars" >/dev/null
export EDITOR="$(/usr/bin/which nvim)"

if [ -f "/etc/arch-release" ]; then
        export DEBUGINFOD_URLS='https://debuginfod.archlinux.org/'
fi

export GPG_TTY="$(tty)"
export VCPKG_ROOT="$APPS/vcpkg"
export HOMEBREW_NO_ENV_HINTS=1

export LC_ALL=en_GB.UTF-8
export LANG=en_GB.UTF-8

if [ -z "$CC" ]; then
        export CC=gcc
fi

export BAT_STYLE=plain
export BAT_THEME=ansi

PATH=""
PATH+=":$CMD/sh" # ed override
if [ "$DEVICE" = "mac" ]; then
        PATH+=":/opt/homebrew/bin"
        PATH+=":/opt/homebrew/sbin"
        PATH+=":/usr/sbin"
        PATH+=":/usr/bin"
        PATH+=":/sbin"
        PATH+=":/Applications/Docker.app/Contents/Resources/bin"
fi
PATH+=":/bin"
PATH+=":$XDG_DATA_HOME/../bin"
PATH+=":$BIN"
PATH+=":$CMD/bin"
PATH+=":$CARGO_HOME/bin"
PATH+=":$BUN_INSTALL/bin"
PATH+=":$GOROOT/bin"
PATH+=":$GOPATH/bin"
PATH+=":$APPS/flutter/bin"
PATH+=":$ANDROID_HOME/cmdline-tools/latest/bin"
export PATH

export RUSTUP_HOME="$DATA/rustup"
export SCCACHE_DIR=$DATA/sccache
export RUSTC_WRAPPER=$(/usr/bin/which sccache)
export RUST_SRC="$CARGO_HOME/registry/src/"
export RUSTDOCFLAGS="-D warnings"
export CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true

#############################
### rebuild changed utils ###
#############################

[ -z "$1" ] && (mb &)
disown 2>/dev/null

###########
### PS1 ###
###########

if [ "$(whoami)" = "root" ]; then
        export PS1='#$(ps1)'
else
        export PS1='$(ps1)'
fi

#################
### man pages ###
#################

export MANSECT=3:2:1:8:5:4:9

export LESS="-R"
export MANPAGER='less -P "man"'

export LESS_TERMCAP_mb=$'\E[1;31m' # begin blinking
export LESS_TERMCAP_md=$'\E[1;35m' # begin bold
export LESS_TERMCAP_me=$'\E[0m'    # end mode
export LESS_TERMCAP_se=$'\E[0m'    # end standout-mode
export LESS_TERMCAP_so=$'\E[1;33m' # begin standout-mode
export LESS_TERMCAP_ue=$'\E[0m'    # end underline
export LESS_TERMCAP_us=$'\E[1;32m' # begin underline

######################
### other settings ###
######################

umask 077 # default permissions on file are w/o perms to go

###################
### BASH VS ZSH ###
###################

if [ -n "$BASH_VERSION" ]; then
        sh=bash
else if [ -n "$ZSH_VERSION" ]; then
        sh=zsh
else
        echo "Unsupported shell"
fi; fi

###########
### fzf ###
###########

if [ -z "$FZF" ]; then
        FZF=fzf
fi
if [ "$sh" = "bash" ]; then
        eval "$($FZF --bash)"
else
        eval "$($FZF --zsh)"
fi

###############
### history ###
###############

export HISTSIZE=4294967295
export HISTFILESIZE=$HISTSIZE
export SAVEHIST=$HISTSIZE
export HISTFILE="$SECRET/${sh}_history"
export HISTTIMEFORMAT='%F-%H-%M-%S '
export HISTCONTROL=ignoredups

if [ "$sh" = "bash" ]; then
        shopt -s histappend
else
        setopt histignoredups
fi

############################
### reload last location ###
############################

export LAST_LOCATION_FILE="$LOGS/last_location.log"
n "$LAST_LOCATION_FILE"
builtin pushd "$(<$LAST_LOCATION_FILE)" >/dev/null

################
### handlers ###
################

command_not_found_handle() {
        l "%1Command not found: %2$1%1.%_" >&2
        return 6
}

command_not_found_handler() {
        command_not_found_handle "$1"
}

prompt() {
        pwd >"$LAST_LOCATION_FILE"
        history -a
}

unset PROMPT_COMMAND
export PROMPT_COMMAND=prompt

precmd() {
        pwd >"$LAST_LOCATION_FILE"
        fc -AI
}

###############
### aliases ###
###############

if [ "$sh" = "bash" ]; then
        . "$CMD/sh/aliases"
fi

########################################
### open alacritty with right config ###
########################################

# on macos i can't source the bash_profile before X
# so I need to respawn the terminal after running it

if [ "$(uname)" = "Darwin" ]; then
        case $- in
        *i*)
                if [ -z "$ALACRITTY_LOG" ]; then
                        exec alacritty &
                        disown
                        exit
                else
                        alacritty msg config "font.size = 15"
                fi
                ;;
        esac
fi
