#!/bin/sh

#########################
# load custom variables #
#########################

[ -z "$FILES" ] && export FILES="$HOME/.files"

[ -f "$FILES/.secret/vars" ] && . "$FILES/.secret/vars" >/dev/null

export DOT="$FILES/dotfiles"
export CMD="$DOT/cmd"
export CONFIG="$DOT/config"
export ETC="$DOT/etc"
export APPS="$FILES/.apps"
export DATA="$FILES/.data"
export DEV="$FILES/.dev"
export LOGS="$DATA/logs"
export SECRET="$FILES/.secret"
export WASTE="$FILES/.waste"

#############################
# global location variables #
#############################

export XDG_CONFIG_HOME="$CONFIG"
export XDG_DATA_HOME="$DATA/local/share"
export XDG_CACHE_HOME="$DATA/local/cache"
export XDG_STATE_HOME="$DATA/local/state"

#############################
# custom location variables #
#############################

export NPM_CONFIG_USERCONFIG="$CONFIG/npm/config"
export NPM_CONFIG_CACHE="$CONFIG/npm/cache"
export INPUTRC="$CONFIG/inputrc"
export IPYTHONDIR="$DATA/ipython"
export SAGE_ROOT="$DATA/sage_root"
export WGETRC="$DATA/wget-hsts"
export XAUTHORITY="$DATA/Xauthority"
export DOT_SAGE="$DATA/sage_dot"
export GNUPGHOME="$DATA/gnupg"
export NODE_REPL_HISTORY="$DATA/repl/node_repl_history"
export TS_NODE_HISTORY="$DATA/repl/ts_node_repl_history"
export PYTHON_HISTORY="$DATA/repl/python_history"
export BUN_INSTALL="$DATA/bun"
export CARGO_HOME="$DATA/cargo"
export RUSTUP_HOME="$DATA/rustup"
export NVM_DIR="$DATA/nvm"
export GH_BINPATH="$DATA/git/gh"
export GEM_HOME="$DATA/gem/install"
export GEM_PATH="$DATA/gem/install"
export GEM_SPEC_CACHE="$DATA/gem/specs"
export CODE_EXTS_PATH="$DATA/code-extensions"

####################
# global variables #
####################

export CC="cc"

if [ -f "/etc/arch-release" ]; then
	export DEBUGINFOD_URLS='https://debuginfod.archlinux.org/'
fi

[ -z "$EDITOR" ] && export EDITOR="/bin/nvim"

export GPG_TTY="$(tty)"
export GPG_TTY
export VCPKG_ROOT="$APPS/vcpkg"

export HISTSIZE=4294967295
export HISTFILESIZE=4294967295
export HISTFILE="$SECRET/bash_history"
export HISTTIMEFORMAT='%F-%H-%M-%S '

export LS_COLORS="$LS_COLORS:'di=0;35:'"

export MANSECT=3:2:1:8:5:4:9

export LC_ALL=en_GB.UTF-8
export LANG=en_GB.UTF-8

export PATH=":/usr/bin:$CMD/sh:$CMD/bin:$CARGO_HOME/bin:$BUN_INSTALL/bin:/home/b/.files/.data/local/share/gem/ruby/3.4.0/bin"

################
# load aliases #
################

. "$CMD/sh/aliases"

#########################
# rebuild changed utils #
#########################

cup &
disown

########################
# reload last location #
########################

export LAST_LOCATION_FILE="$LOGS/last_location.log"
p "$(<$LAST_LOCATION_FILE)"

prompt() {
	[ "$DEVICE" = "acer" ] && [ -d "$HOME/.vscode-oss" ] && rmm -rf "$HOME/.vscode-oss"
	pwd >"$LAST_LOCATION_FILE"
}

export PROMPT_COMMAND=prompt

#######
# PS1 #
#######

if [ "$(whoami)" = "root" ]; then
	export PS1='#$(ps1)'
else
	export PS1='$(ps1)'
fi

command_not_found_handle() { eh "Command not found: '$1'."; }
