#!/bin/sh

l="$LOGS/sound-"

if [ "$1" = "logs" ]; then
        bat "$l*"
        exit 0
fi

if [ -n "$1" ]; then
        echo "Usage: $0 [logs]"
        exit 1
fi

pipewire >"$l-1" 2>"$l-2" &
pipewire-pulse >"$l-pulse-1" 2>"$l-pulse-2" &
wireplumber >"$l-wire-1" 2>"$l-wire-2" &
