#!/bin/sh

set -eo pipefail

l="$LOGS/sound-"

if [ "$1" = "logs" ]; then
        bat $l*
        exit 0
fi

if [ "$1" = "fg" ]; then
        pipewire &
        pipewire-pulse &
        wireplumber &
        disown
        exit 0
fi

if [ "$1" = "kill" ]; then
        killapp pipewire
        killapp wireplumber
        exit 0
fi

if [ -n "$1" ]; then
        echo "Usage: $0 [logs|fg|--help]"
        exit 1
fi

for f in $l*; do
        mv $f $f.old
done

pipewire >"$l-1" 2>"$l-2" &
pipewire-pulse >"$l-pulse-1" 2>"$l-pulse-2" &
wireplumber >"$l-wire-1" 2>"$l-wire-2" &
disown
