#!/bin/bash

set -eo pipefail

l="$LOGS/sound-"
names="pipewire pipewire-pulse wireplumber"

runs() { return $(ps -ax | awk '{print $5}' | g qi "^$1$"); }
mov() {
        for f in $l*; do
                [ -f $f ] &&
                        mv $f $f.old
        done
}
chk() {
        x=
        for f in $names; do
                runs $f && x+="$f-"
        done
        [ -n "$x" ] && {
                l "$x is already running"
                exit 1
        }
}

case "$1" in
"logs")
        for f in $names; do
                la $f
                v $l$f
        done
        ;;
"kill")
        for f in $names; do
                la $f
                killapp $f
        done
        ;;
"ps")
        for f in $names; do
                lw "$f: "
                runs $f && l "running" || l "stopped"
        done
        ;;
"")
        mov
        chk
        for f in $names; do
                $f >"$l-$f-1" 2>"$l-$f-2" &
        done
        disown
        ;;
"fg")
        mov
        chk
        for f in $names; do
                runs $f
                $f &
        done
        wait
        ;;
*)
        le "Usage: $0 [logs|kill|fg|ps|--help]"
        ;;
esac
