#!/bin/bash

if [ -z "$1" ]; then
        pwd
        return
fi
if [ -n "$2" ]; then
        for p in $@; do
                lw "%6$p: "
                wi $p
        done
        return
fi

ty=$(type $1 2>/dev/null || file "$1" 2>&1 || true)

findin() {
        if [ -z "$3" ]; then
                path=$(ff . "$1" | gg "/$2$" | g v "$DOT/cmd/src/zlib")
        else
                path=$(ff . "$1" | gg "$2" | g v "$DOT/cmd/src/zlib")
        fi
        if [ -n "$path" ]; then
                l "$path"
                return 0
        else
                return 1
        fi

}

case "$ty" in
*"No such file or directory"*)
        paths="$DOT/cmd $DOT /etc"
        for p in $paths; do
                findin "$p" "$1" && return
        done
        for p in $paths; do
                findin "$p" "$1" f && return
        done
        ;;
"$1 is a shell builtin")
        l "builtin"
        ;;
"$1 is a shell keyword")
        l "keyword"
        ;;
"$1 is aliased to \`"*)
        alias=${ty#"$1 is aliased to \`"}
        alias=${alias%?}
        l "$alias"
        ;;
"$1 is hashed ("*)
        path=${ty#"$1 is hashed ("}
        path="${path%?}"
        path="$(readlink -f $path)"
        l "$path"
        ;;
"$1 is "*)
        path=${ty#"$1 is "}
        path="$(readlink -f $path)"
        l "$path"
        ;;
"$1: directory")
        path="$(readlink -f $1)"
        l "$path"
        ;;
"$1: "*)
        ft=${ty#"$1: "}
        l $ft
        ;;
*)
        l "%1unhandled case: %3$ty"
        ;;
esac
