#include "libcmd.h"

make_single("g",
            "rg",
            "--no-ignore",
            "=.--hidden",
            "=N--no-line-number",
            "=M--max-columns",
            "=U--multiline",
            "--ignore-case",
            "=v--invert-match",
            "--max-count",
            "=F--fixed-strings",
            "=s--case-sensitive",
            "=S--smart-case",
            "--count",
            "=I--no-filename",
            "-w",
            "=n--line-number",
            "--only-matching",
            "-e",
            "--quiet",
            "--pretty",
            "-u",
            "=A--after-context",
            "=B--before-context",
            "--type",
            "--binary",
            "=H--with-filename",
            "-l",
            "=C--color=always", )
