#include "libcmd.h"

/// TODO: a number after ilon should be integer not HEAD
/// TODO: add a iorb to rebase edit on one commit only w/o editor
/// TODO: on git rebase conflicts, display the list of CONFLICTS only (and put
/// the full log in a file in del?)
/// TODO: same for git merge
/// TODO: interactive git add that let's me select files to add.

static const Cmd COMMANDS[] = {
    headcmd("a", "add", "-p", ".", "--intent-to-add", "-e", "--all", ),

    headcmd("br",
            "branch",
            "-a",
            "-d",
            "--force",
            "-D",
            "-m",
            "-M",
            "-r",
            "-u",
            "--contains",
            "--show-current", ),
    headcmd("bi",
            "bisect",
            "start",
            "bad",
            "good",
            "run",
            "=ereset",
            "visualize",
            "=a--stat", ),

    headcmd("cl", "clone", "--depth", ),
    headcmd("ck", "checkout", "-t", "--orphan", "-b", ),
    headcmd("cp", "cherry-pick", "--abort", "--continue", ),
    headcmd("cg",
            "config",
            "--add",
            "credential.helper",
            "diff.tool",
            "=euser.email",
            "false",
            "--global",
            "=hurl.\"https://github.com/\".insteadOf",
            "init.defaultBranch",
            "--list",
            "=nuser.name",
            "=odifftool.prompt",
            "pull.rebase",
            "--replace-all",
            "set",
            "=Scommit.gpgsign",
            "true",
            "=upush.autoSetupRemote",
            "=vnvimdiff",
            "=wurl.\"https://github.com/t-webber/\".insteadOf", ),
    headcmd("c",
            "commit",
            "-m",
            "--amend",
            "-q",
            "-S",
            "--no-edit",
            "--quiet",
            "=b--allow-empty",
            "=g--allow-empty-message",
            "--reset-author", ),

    headcmd("do", "difftool", "--cached", ),
    headcmd("d", "diff", "--shortstat", "--cached", "--exclude", ),

    headcmd("e", "fetch", "--all", "--unshallow", "--prune", "--tags", ),

    headcmd("f", "fsck", "--no-reflogs", "--lost-found", ),

    headcmd("gc", "gc", "--prune=now", "--aggressive", ),
    headcmd("g", "grep", "-F", "--all-match", "-n", ),

    headcmd("help", "status", ),

    headcmd("i", "init", ),

    headcmd("ls", "ls-files", ),
    headcmd("lr",
            "reflog",
            "--graph",
            "-n",
            "expire",
            "=w--expire=now",
            "--all",
            "-p",
            "=a--name-status", ),
    headcmd("l",
            "log",
            "--oneline",
            "--graph",
            "-n",
            "-p",
            "=a--name-status",
            "--stat", ),

    headcmd("mv", "move", ),
    headcmd("m",
            "merge",
            "=w--allow-unrelated-histories",
            "--abort",
            "--continue", ),

    headcmd("n", "clean", "-f", "-f", "-d", "-x", "--recurse-submodules", ),

    headcmd("ph",
            "push",
            "=F--force",
            "=f--force-with-lease",
            "-d",
            "-u",
            "--quiet",
            "--tags",
            "=gHEAD:refs/for/master",
            "=GHEAD:refs/for/main", ),
    headcmd("pl", "pull", "-a", "-f", "--quiet", ),

    headcmd("rb",
            "rebase",
            "--abort",
            "--continue",
            "--edit-todo",
            "--quit",
            "-i",
            "--root", ),
    headcmd("rm", "rm", "-f", "-r", "--cached", ),
    headcmd("ro", "restore", "-S", "-W", "--staged", ".", ),
    headcmd("rs", "reset", "--hard", "--soft", ".", ),
    headcmd("rt", "remote", "-v", "set-url", "add", "=wshow", "remove", ),
    headcmd("rp", "rev-parse", "--show-toplevel", "--git-common-dir", ),
    headcmd("rl", "rev-list", "--all", ),
    headcmd("rw", "review", "-d", ),

    headcmd("sh",
            "stash",
            "pop",
            "drop",
            "clear",
            "show",
            "apply",
            "list",
            "-m",
            "--keep-index",
            "=w--all",
            "=S--staged", ),
    headcmd("sm",
            "submodule",
            "update",
            "--init",
            "--recursive",
            "d",
            "deinit",
            "-f",
            "-all",
            "--cache", ),
    headcmd("sw", "switch", "-C", "-c", ),
    headcmd("so", "show", "--stat", ),
    headcmd("s", "status", "--ignored", ),

    headcmd("t", "tag", "-d", ),

    headcmd("v", "version", ),

    headcmd("w", "worktree", "add", "remove", "move", "list", "-f", ),

    headcmd("y",
            "apply",
            "-R",
            "=s--ignore-space-change",
            "=w--ignore-whitespace",
            "--reject", ),
};

static const Manual MANUAL[] = {{'H', "HEAD"},
                                {'F', "FETCH_HEAD"},
                                {'^', "HEAD"},
                                {'?', "--help"},
                                {'O', "origin"},
                                {'U', "upstream"},
                                {'E', "master"},
                                {'C', "--color=always"},
                                {'-', "--"},
                                {'.', ".."},
                                {'M', "main"},
                                {'P', "--no-pager"},
                                {'G', "--paginate"}};

make_settings(SETTINGS, COMMANDS, MANUAL);

make_main(SETTINGS, "git")
