#!/bin/bash

print() { echo -e "\x1b[33m==== Setup:$1\x1b[0m"; }

here=$(dirname $0)

print stage1

"$here/setup.stage1.sh"

print ttys

for x in 2; do
        agetty --noclear "tty$x" linux &
done

print user

runuser -u b -- "$here/setup.user.sh" &

disown
