#!/bin/sh

start=$(date +%s%N)

f=/del/.waste/init-shut
mv $f $f.old

print() {
        local end=$(date +%s%N)
        local elapsed=$((end - start))
        echo "  (took $((elapsed / 1000000)) ms)" >>$f
        echo "$1..." >>$f
        echo -e "\x1b[33m├─── WebberOS:$1\x1B[0m"
        start=$(date +%s%N)
}

err() {
        echo -e "\x1b[31m├─── WebberOS:[$1]"
        export DISPLAY=:0
        /del/.bin/herbe br:#f00 fg:#f00 "!!! $1 !!! "
        exit 1
}

##################
print "$1"
##################

[ ! -f /bin/init ] && {
        err "no init"
}

[ ! -f /boot/vmlinuz-linux ] ||
        [ ! -f /boot/intel-ucode.img ] ||
        [ ! -f /boot/initramfs-linux.img ] && {
        err "missing boot files"
}

##################
print "stopping"
##################

kill -15 -1

for i in $(seq 1 100); do
        echo "=== $i ===" >>$f
        procs=$(pgrep -a -v -x 'init|sh|shutdown' | grep -v '\[.*\]')
        echo "$procs" | awk '{print $2}' | sort -n | uniq -c >>$f
        if ! pgrep -a -v -x 'init|sh|shutdown' | grep -vq '\[.*\]'; then
                break
        fi
        sleep 0.1
done

##################
print "killing"
##################

kill -9 -1

##################
print "synchronising"
##################

sync

##################
print "remounting"
##################

echo u >/proc/sysrq-trigger

##################
print "unreachable"
###################

if [ "$1" = "reboot" ]; then
        echo b >/proc/sysrq-trigger
else
        echo o >/proc/sysrq-trigger
fi
