#!/bin/sh

setxkbmap fr &

bspc monitor -d term edit browser com

bspc config border_width 1
bspc config window_gap 0

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config normal_border_color \#000000
bspc config focused_border_color \#550000
bspc config presel_feedback_color \#000000

bspc config top_padding 0
bspc config top_monocle_padding 0

(
        bspc desktop -f browser
        brave >/dev/null &
        sleep 1
        bspc desktop -f term
        alacritty
) &

slock && (
        gui_startup & # >"$LOGS/gui_startup.log" 2>&1 &
)
