#!/bin/bash

. /etc/bash.bashrc

# echo "inside"
# date
# echo "if bspwm hangs, look for bspwm/socket"
# echo "inside xinit" >/home/b/x
# date >>/home/b/x
# rm -f /home/b/bsp

export GTK_THEME=Adwaita:dark
export PASSWORD_STORE_BACKEND=plain
export CHROME_SECRET_STORE=gnome
export XCURSOR_THEME=HUD_Machine_Red_Cursors
export XCURSOR_SIZE=80

# echo "after at loop" >>/home/b/x
# date >>/home/b/x

# LOGS=/home/b/.files/.data/logs
# date >$LOGS/bspwm.log
# echo "[xinitrc] HOME=$HOME XDG_CONFIG_HOME=$XDG_CONFIG_HOME" >>$LOGS/bspwm.log
exec bspwm # >>$LOGS/bspwm.log

# echo "unreachable" >>/home/b/x
# date >>/home/b/x
