#!/bin/sh

sudo systemctl start iwd systemd-resolved
systemctl --user start pipewire.socket wireplumber pipewire-pulse.socket

xrandr --output DP-0 --scale 1.5x1.5

dunst &
alacritty &

. "/home/b/.bashrc"

/usr/bin/rm -rf "$FILES/.waste"
mkdir -p "$FILES/.waste"

mkdir -p "$LOGS"
echo "$(date '+%d/%m/%y | %H:%M')" > "$LOGS/startup.txt"

while [[ -z "$(sudo iwctl station wlan0 show | grep ' connected')" ]]; do
	sleep 10
done

alacritty -e bun update -g &
alacritty -e paru -Syyu --noconfirm &
alacritty -e ru &
alacritty --hold -e informant check &
